services:
  - type: web
    name: pos-backend
    env: python
    buildCommand: "./render_build.sh"
    startCommand: "cd pos-backend-django && gunicorn pos_backend.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "pos-backend.onrender.com"
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        value: ""

staticSites:
  - name: pos-frontend
    buildCommand: "cd pos-frontend && npm install && npm run build"
    publishPath: "./pos-frontend/dist"
    envVars:
      - key: VITE_API_URL
        value: "https://pos-backend.onrender.com/api"
